# Generated by Django 3.2 on 2021-04-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.playercoins')),
            ],
        ),
    ]
