# Generated by Django 3.2 on 2021-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='team_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moves',
            name='team_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moves',
            name='team_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moves',
            name='team_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moves',
            name='team_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moves',
            name='team_6',
            field=models.IntegerField(default=0),
        ),
    ]
