# Generated by Django 3.2 on 2021-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20210412_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='previous_roll',
            field=models.IntegerField(default=0),
        ),
    ]
