# Generated by Django 3.2 on 2021-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_moves_previous_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='game_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertycard',
            name='mortgaged',
            field=models.BooleanField(default=False),
        ),
    ]
