# Generated by Django 3.2 on 2021-04-15 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_auto_20210414_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='data_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
