# Generated by Django 3.2 on 2021-04-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_transactions_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycard',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
